Traceback (most recent call last):
  File "/home/anatolii-shara/Documents/mlops_projector/hw6/src/rec_sys/pipeline.py", line 70, in <module>
    main()
  File "/home/anatolii-shara/Documents/mlops_projector/hw6/src/rec_sys/pipeline.py", line 50, in main
    books   = load_books("/home/anatolii-shara/Documents/mlops_projector/hw5/data/data/ukr_books_dataset.csv")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anatolii-shara/Documents/mlops_projector/hw6/src/rec_sys/pipeline.py", line 16, in load_books
    df = pd.read_csv(path)
         ^^^^^^^^^^^^^^^^^
  File "/home/anatolii-shara/Documents/mlops_projector/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anatolii-shara/Documents/mlops_projector/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anatolii-shara/Documents/mlops_projector/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anatolii-shara/Documents/mlops_projector/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/anatolii-shara/Documents/mlops_projector/venv/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anatolii-shara/Documents/mlops_projector/hw5/data/data/ukr_books_dataset.csv'
